global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka Exporter - Provides Kafka metrics
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 10s
    metrics_path: /metrics

  # Kafka Broker JMX metrics (optional - for more detailed broker metrics)
  - job_name: 'kafka-broker'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 30s 